#!/bin/bash

echo "🔍 Checking App ID Configuration..."
echo "=================================="

echo ""
echo "📱 Your App ID: com.cybersimply.app"
echo ""
echo "🔧 Required Capabilities:"
echo "  ✅ Apple Sign In"
echo "  ✅ In-App Purchases"
echo ""
echo "🌐 To fix this issue:"
echo "1. Go to: https://developer.apple.com/account/resources/identifiers/list"
echo "2. Find: com.cybersimply.app"
echo "3. Click 'Edit'"
echo "4. Enable 'Sign In with Apple'"
echo "5. Enable 'In-App Purchase'"
echo "6. Click 'Save'"
echo "7. Go back to Xcode"
echo "8. Try 'Try Again' button"
echo ""
echo "📋 Alternative: Create New App ID"
echo "1. Create new App ID: com.cybersimply.app.v2"
echo "2. Enable both capabilities"
echo "3. Update bundle ID in Xcode"
echo "4. Archive again"
echo ""
echo "🎯 This should fix the provisioning profile mismatch!"
